### ISSUE TITLE
adding words to the list

### ISSUE THREAD

**Issue by dwrensha** [dwrensha/acronymy.net#3]
I can manually add words to the list by running the [add-words-to-wordlist.py](https://github.com/dwrensha/acronymy-workers/blob/main/add-words-to-wordlist.py) script.

We might consider adding a way for a user to request that a word be added to the list. Maybe the error page for "word not in list" could include a form for that. (And then I would periodically look at the requests and sometimes grant some of them.)

We might even allow self-service adding of words to the list, but that seems scary and would require careful content moderation.

**Comment by DecimalTurn** [comment]
The word "website" is currently missing. Could you please add it?

**Comment by dwrensha** [comment]
I added a form that allows users to suggest new words, subject to moderation by me: https://github.com/dwrensha/acronymy.net/commit/9b5a198a0398f5e263aaf308160bbf2145204616

https://acronymy.net/suggest-word
https://acronymy.net/define/website
