### ISSUE TITLE
Feature request: Random defined/undefined word

### ISSUE THREAD

**Issue by JapanYoshi** [dwrensha/acronymy.net#6]
I’d like it if the site let me view a random defined word (to show off the site to others) and a random undefined word (to find new words to backronymize).

**Comment by dwrensha** [comment]
I wonder where the links to this functionality would live? I guess there could be new buttons on the homepage https://acronymy.net

On the backend, adding this kind of thing would be easier if we moved to a different database. See #7.

**Comment by mdmunoz** [comment]
Random undefined words would be great. Thinking of new words can be tricky, since readily-guessable words are often taken.

**Comment by dwrensha** [comment]
completed in 30f936671ae1e36d464065161239ee0c15ee5a28
