### ISSUE TITLE
Uppercase problem when submitting definition for missing words

### ISSUE THREAD

**Issue by DecimalTurn** [dwrensha/acronymy.net#8]
Oops, seems like the field for submitting defintion for words that are not in the list doesn't perform lowercase transformation.

Example occurence: https://acronymy.net/define/xenically

Related to: https://github.com/dwrensha/acronymy.net/issues/3

**Comment by dwrensha** [comment]
Good catch. Fixed in https://github.com/dwrensha/acronymy.net/commit/c88573ab6fcc675dac8eace3fcc9aaffde75da34.
